Add more documentation on bundles to README
workarea-commerce/workarea-product-bundles pull request #9
Opened 2020-09-17 19:11 UTC by mttdffy

BUNDLES-3

I don't have a clear enough vision on how to improve this further, so here it is. Let me know if you have any thoughts.

2020-09-18 12:40 UTC, bencrouse commented on README.md
> +* adds the `defer_to_components` inventory policy which is used for kits to allow inventory to be determined by the SKUs which make up a particular kit variant.
```suggestion
* Adds the `defer_to_components` inventory policy which is used for kits to allow inventory to be determined by the SKUs which make up a particular kit variant.
```

2020-09-18 12:40 UTC, bencrouse commented on README.md
> +For some bundles, this is simply a way to display related products together on a single product detail page. In this plugin, we call those **discrete bundles**, which always show each individual prod
```suggestion
For some bundles, this is simply a way to display related products together on a single product detail page. In this plugin, we call those **discrete bundles**, which always show each individual product within the bundle and allow any or all of the products to be added to cart. Each individual product will show as a separate item in the cart and throughout checkout.
```

2020-09-18 12:40 UTC, bencrouse commented on README.md
> +A package product is the most basic product bundle type. A package displays bundled products on a single detail page where a customer can select options and add each individual product to their cart
```suggestion
A package product is the most basic product bundle type. A package displays bundled products on a single detail page where a customer can select options and add each individual product to their cart one at a time. Each product within a package product displays its own options, quantity, and add to cart button. The package product itself is never added directly to cart, but rather serves as a container of those related products.
```

2020-09-18 12:40 UTC, bencrouse commented on README.md
> +![Kit Diagram](kit_diagram.png)
Nice, this is very helpful.

2020-09-21 15:56 UTC, ebigler commented
Looks good to me! thanks

2020-09-21 15:58 UTC, ebigler approved these changes
As I mentioned in the standup meeting, my only suggestion is maybe mentioning something about kits having price adjustments but otherwise this looks good.

2020-09-21 16:39 UTC, tubbo requested changes

2020-09-21 16:39 UTC, tubbo commented on README.md
> +The variants in the kit are represented to the customer like variants of a regular product from the detail page through checkout. Once an order containing a kit is placed, the items within the kit ar
```suggestion
The variants in the kit are represented to the customer like variants of a regular product from the detail page through checkout. Once an order containing a kit is placed, the items within the kit are expanded out of the kit as separate order items, to allow for individual tracking of each item's status through fulfillment.
```

2020-09-22 12:44 UTC, bencrouse approved these changes

2020-09-22 12:44 UTC, merged